word_list = ['Fumikage Tokoyami'
'Gon Freeces'
'Killua Zoldyk'
'Tsuyu Asui'
'Karma Akabane'
'Ryunosuke Chiba'
'Jean Kirschtein'
'Nagisa Shiota'
'Reiner Braun'
'Kurapika'
'Hanta Sero'
'Adam'
'Misa'
'Mezo Shoji'
'Conny Springer'
'Eijiro Kirishima'
'Marco Bodt'
'Erwin Smith'
'Shoto Todoroki', 
'Hawks'
'Annie Leonhart'
'Irīna Yelabitch'
'Langa Hasegawa'
'Kurosensei'
'Joe'
'L'
'Levi Ackerman'
'Cherry'
'Eren Jaeger'
'Falco'
'Ochaco Uraraka'
'Mikasa Ackermann'
'Miya'
'Reki'
'Kyoka Jiro'
'Yuba Isogui'
'Mashirao Ojiro'
'Katsuki Bakugo'
'Momo Yaoyorozu'
'Mina Ashido'
'Tenya Ida'
'Kurasama'
'Bertholdt Hoover'
'Gabi Braun'
'Hisoka'
'Light Yagami']